Remove references to the `light-level` CSS media feature.
w3c/ambient-light pull request #76
Opened 2021-12-07 17:22 UTC by rakuco

It was removed from the Media Queries Level 5 spec in
w3c/csswg-drafts@f5b663c27d5a in favor of the `prefers-contrast` and
`prefers-color-scheme` media features. Reword the paragraph to mention those
instead.

While here, change the biblio for the `matchMedia` API from CSSOM to
CSSOM-VIEW-1, which is where it is actually specified.

2021-12-07 17:23 UTC, rakuco commented
@anssiko `prefers-contrast` and `prefers-color-scheme` aren't directly related to ambient light level readings like `light-level` was, so I'm not 100% satisfied with how that paragraph starts but I also can't think of a better version right now :/

2021-12-08 14:39 UTC, anssiko commented
Thanks, this is a good update.

I think it'd be useful historical context to retain in the spec that CSS WG once considered but then dropped the 'light-level' CSS feature. Why it might be significant for future generations is that the existence of that CSS feature was once used as an argument for not needing this API. Given the new prefers-* CSS features are further abstracted this means the use cases addressed by the new CSS features and this API are also increasingly more distinct. If you agree, can you update accordingly?

2021-12-08 14:39 UTC, anssiko requested changes
As in the comment.

2021-12-08 16:10 UTC, rakuco commented
> I think it'd be useful historical context to retain in the spec that CSS WG once considered but then dropped the 'light-level' CSS feature. Why it might be significant for future generations is that the existence of that CSS feature was once used as an argument for not needing this API. Given the new prefers-* CSS features are further abstracted this means the use cases addressed by the new CSS features and this API are also increasingly more distinct. If you agree, can you update accordingly?

I've reworded the paragraph a bit and added a note mentioning `light-level` and pointing to the commit that removed it from the spec. Please take another look, I'm not sure if we need to be more explicit about this change making this spec more distinct from MEDIAQUERIES-5.

2021-12-08 16:23 UTC, anssiko approved these changes
Thanks! LGTM with a typo nit.

2021-12-08 16:23 UTC, anssiko commented on index.bs
> +influenced a device's measured ambient light level are best served by the the
```suggestion
influenced by a device's measured ambient light level are best served by the the
```

2021-12-08 16:25 UTC, merged